###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mysql:
      image: mysql:8.0
      container_name: teste-requisito-rh-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=teste-requisito-rh
        - MYSQL_USER=teste-requisito-rh
        - MYSQL_PASSWORD=teste-requisito-rh
      ports:
        - "8094:3306"

    webserver:
      image: nginx:alpine
      container_name: teste-requisito-rh-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8092:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: teste-requisito-rh-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini

